# Generated by Django 3.1.13 on 2021-10-31 08:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=50)),
                ('income_group', models.CharField(choices=[('0-25k', '0-$25k'), ('>$70', '>$70K'), ('$25-$70', '$25-$70K')], max_length=50)),
                ('region', models.CharField(choices=[('east', 'east'), ('west', 'west'), ('south', 'south'), ('north', 'north')], max_length=50)),
                ('marital_status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fuel', models.CharField(choices=[('CNG', 'cng'), ('DIESEL', 'diesel'), ('PETROL', 'petrol')], max_length=50)),
                ('vehicle_segment', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=50)),
                ('premium', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)])),
                ('date_of_purchase', models.DateTimeField()),
                ('bodily_injury_liability', models.BooleanField(default=False)),
                ('personal_injury_liability', models.BooleanField(default=False)),
                ('property_damage_liability', models.BooleanField(default=False)),
                ('collision', models.BooleanField(default=False)),
                ('comprehensive', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='base.customer')),
            ],
            options={
                'verbose_name': 'Policy',
                'verbose_name_plural': 'Policies',
                'ordering': ('created_at',),
            },
        ),
    ]
